# Revising Aggregations - The Count Function
SELECT COUNT(*)
FROM CITY
WHERE POPULATION > 100000;


# Revising Aggregations - The Sum Function
SELECT SUM(POPULATION)
FROM CITY
WHERE DISTRICT = 'California';


# Revising Aggregations - Averages
SELECT AVG(POPULATION)
FROM CITY
WHERE DISTRICT = 'California';


# Average Population
SELECT AVG(POPULATION)
FROM CITY;


# Japan Population
SELECT SUM(POPULATION)
FROM CITY
WHERE COUNTRYCODE = 'JPN';


# Population Density Difference
SELECT MAX(POPULATION) - MIN(POPULATION)
FROM CITY;


# The Blunder
SELECT CAST(CEILING(AVG(CAST(SALARY as FLOAT))-AVG(CAST(REPLACE(STR(SALARY), '0', '') AS FLOAT))) AS INT) 
FROM EMPLOYEES;


# Top Earners
SELECT TOP 1 (MONTHS*SALARY) AS EARNINGS, COUNT(*)
FROM EMPLOYEE
GROUP BY MONTHS*SALARY
ORDER BY COUNT(*) DESC;
